---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=256.2
  sha1: ff2f4e16e02f66b31c595196052a809100cfd5a8
- name: bosh-virtualbox-cpi
  url: https://bosh.io/d/github.com/cppforlife/bosh-virtualbox-cpi-release?v=0.0.1
  sha1: 03450cd53bcf2ef00207da3b68f709981a3b3a7d

resource_pools:
- name: vms
  network: private
  stemcell:
    url: file://~/Downloads/bosh-stemcell-3232.4-vsphere-esxi-ubuntu-trusty-go_agent.tgz
  cloud_properties:
    cpu: 2
    ram: 3072
    disk: 16_384

disk_pools:
- name: disks
  disk_size: 20_000

networks:
- name: private
  type: manual
  subnets:
  - range:   192.168.50.0/24
    gateway: 192.168.50.1
    dns:     [192.168.50.1]
    cloud_properties:
      name: vboxnet0

instance_groups:
- name: bosh
  instances: 1
  jobs:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}

  - name: virtualbox_cpi
    release: bosh-virtualbox-cpi
    properties:
      host: &host "192.168.50.1"
      username: &username {{username}}
      private_key: &private_key {{private_key}}

      agent: {mbus: "nats://nats:nats-password@192.168.50.6:4222"}
      ntp: [0.pool.ntp.org, 1.pool.ntp.org]
      blobstore:
        address: 192.168.50.6
        port: 25250
        provider: dav
        director: {user: director, password: director-password}
        agent: {user: agent, password: agent-password}

  resource_pool: vms
  persistent_disk_pool: disks
  networks:
  - name: private
    static_ips: [192.168.50.6]

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    blobstore:
      address: 192.168.50.6
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: vbox-bosh
      db: *db
      cpi_job: virtualbox_cpi
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

cloud_provider:
  template: {name: virtualbox_cpi, release: bosh-virtualbox-cpi}
  mbus: "https://mbus:mbus-password@192.168.50.6:6868"
  properties:
    host: *host
    username: *username
    private_key: *private_key

    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    ntp: [0.pool.ntp.org, 1.pool.ntp.org]
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
