azs:
- name: z1
- name: z2

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240

disk_types:
- name: default
  disk_size: 3000

networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.50.0/24
    gateway: 192.168.50.1
    azs: [z1, z2]
    reserved:
    - 192.168.50.6
    dns:
    - 192.168.50.1
    cloud_properties:
      name: vboxnet0

compilation:
  workers: 2
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
